#theme: jekyll-theme-slate
remote_theme: benbalter/retlab

title: PChemGuy
description: Physical Chemist, STEM admirer

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-feed