#theme: jekyll-theme-slate
remote_theme: pmarsceill/just-the-docs

title: "PChemGuy"

webmaster_verifications:
  google: "eeyANkR7sUrPKHD5z5GheWmEg9GY5Sjpn1aCSpbx0J0"
  yandex: "f38641d9b37f88a4"

# Google Analytics Tracking
google_analytics: "UA-197722197-1"
ga_tracking: "UA-197722197-1"

# Yandex Metrica
ya_tracking: "79433089"

# Plugins
plugins:
  - jekyll-seo-tag
