#theme: jekyll-theme-slate
remote_theme: benbalter/retlab

title: "PChemGuy"

# Google Analytics Tracking (optional)
google_analytics: "UA-197722197-1"
ga_tracking: "UA-197722197-1"

webmaster_verifications:
  google: "eeyANkR7sUrPKHD5z5GheWmEg9GY5Sjpn1aCSpbx0J0"
  yandex: "8703f875cde8e0ac"

# Plugins
plugins:
  - jekyll-seo-tag
